version: '3.1'

services:
    web:
        build:
            context: ./docker/web
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                NODE_VERSION: '${NODE_VERSION}'
                POSTGRES_VERSION: '${POSTGRES_VERSION}'
        volumes:
            - ./:/var/www/html
        ports:
            - '${APP_PORT:-80}:80'
            - '443:443'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
        networks:
            - 'brightmoon'
        tty: true

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'brightmoon-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/create-testing-database.sh'
        ports:
            - '${FORWARD_MYSQL_PORT:-3306}:3306'
        networks:
            - 'brightmoon'

    postgres:
        image: postgres:15
        environment:
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
        volumes:
            - brightmoon-postgres:/var/lib/postgresql/data
        ports:
            - '${FORWARD_POSTGRES_PORT:-5432}:5432'
        networks:
            - 'brightmoon'

    adminer:
        image: 'adminer:latest'
        ports:
            - '8084:8080'
        networks:
            - 'brightmoon'
        environment:
            ADMINER_DESIGN: 'pepa-linha'
            ADMINER_DEFAULT_SERVER: mysql
            ADMINER_PLUGINS: 'tables-filter tinymce'

networks:
    brightmoon:
        driver: bridge
volumes:
    brightmoon-mysql:
        driver: local
    brightmoon-postgres:
        driver: local
