#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER www-dev
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ ${ENABLE_SSL} == true ]; then
    if [ -e /var/www/html/docker/web/certs/ssl.crt ]; then
        mkdir -p /etc/apache2/ssl
        cp /var/www/html/docker/web/certs/ssl.crt /etc/apache2/ssl/ssl.crt
        cp /var/www/html/docker/web/certs/ssl.key /etc/apache2/ssl/ssl.key
    fi
    a2enmod ssl
fi

/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
